language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial # 3.7 requires Xenial on Travis
addons:
  apt:
    packages:
      - pandoc
install:
  - pip install .
  - pip install -r tests/requirements.txt
  - pip install -r doc/requirements.txt
  # This is needed in example scripts:
  - pip install pillow
script:
  - python -m pytest
  - python doc/examples/run_all.py
  # This executes the example notebooks and runs the doctests:
  - python -m sphinx doc/ _build/ -b doctest
