language: python
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial # 3.7 requires Xenial on Travis
addons:
  apt:
    packages:
      - pandoc
install:
  - pip install .
  - pip install -r tests/requirements.txt
  - pip install -r doc/requirements.txt
script:
  - python -m pytest
  # This executes the example notebooks:
  - python -m sphinx doc/ _build/ -b dummy
